site_name: Clea
site_url: https://angrybayblade.me/clea
repo_url: https://github.com/angrybayblade/clea/
edit_uri: blob/main/docs/
nav:
  - Command: command.md
  - Group: group.md
  - Parameters: parameters.md   
  - Context: context.md
  - Testing: testing.md
  - Upgrading: upgrading.md
