site_name: Clea
site_url: http://clea.angrybayblade.me/
repo_url: https://github.com/angrybayblade/clea/
edit_uri: blob/main/docs/
extra_css:
  - style.css
nav:
  - Command: command.md
  - Group: group.md
  - Parameters: parameters.md   
  - Context: context.md
  - Testing: testing.md
  - Upgrading: upgrading.md
